# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.model.address: AppBundle\Entity\Address
    app.model.election: AppBundle\Entity\Election
    app.model.election_round: AppBundle\Entity\ElectionRound
    app.model.office: AppBundle\Entity\Office
    app.model.procuration: AppBundle\Entity\Procuration
    app.model.voting_availability: AppBundle\Entity\VotingAvailability
    app.model.voter_invitation: AppBundle\Entity\VoterInvitation

services:
    app.fpdi.writer:
        class: AppBundle\FPDI\FPDIWriter
        arguments:
            - "%cerfa_source_file_path%"
            - "@app.mediator.procuration"
            - "@filesystem"


    app.mediator.office:
        class: AppBundle\Mediator\OfficeMediator
        arguments:
            - "@app.repository.office"
    app.mediator.procuration:
        class: AppBundle\Mediator\ProcurationMediator
        arguments:
            - "@app.repository.procuration"
            - "@doctrine.orm.entity_manager"
            - "%cerfa_output_root_path%"
            - "@en_marche_mailjet.client.transactional"
    app.mediator.user:
        class: AppBundle\Mediator\UserMediator
        arguments:
            - "@app.repository.user"
    app.mediator.voter_invitation:
        class: AppBundle\Mediator\VoterInvitationMediator
        arguments:
            - "@doctrine.orm.entity_manager"
    app.mediator.voting_availability:
        class: AppBundle\Mediator\VotingAvailabilityMediator
        arguments:
            - "@app.repository.voting_availability"
            - "@doctrine.orm.entity_manager"


    app.twig.address_extension:
        class: AppBundle\Twig\AddressExtension
        public: false
        tags:
            - { name: twig.extension }
    app.twig.procuration_extension:
        class: AppBundle\Twig\ProcurationExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.form.handler.procuration_assignation"
    app.twig.ui_extension:
        class: AppBundle\Twig\UiExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.mediator.user"
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        public: false
        tags:
            - { name: twig.extension }

