procuration_unbind:
    path: /{id}/unbind
    methods: GET
    defaults: { _controller: AppBundle:Procuration:unbind }
    requirements:
        id: \d+

procuration_download:
    path: /{id}/download
    methods: GET
    defaults: { _controller: AppBundle:Procuration:download }
    requirements:
        id: \d+

procuration_assign:
    path: /{id}
    methods: POST
    defaults: { _controller: AppBundle:Procuration:assign }
    requirements:
        id: \d+

procuration_delete:
    path: /{id}
    methods: DELETE
    defaults: { _controller: AppBundle:Procuration:delete }
    requirements:
        id: \d+

procuration_index:
    path: /
    methods: GET
    defaults: { _controller: AppBundle:Procuration:index }
