user_new:
    path: /new
    defaults: { _controller: AppBundle:User:new }
    methods: GET|POST

user_edit:
    path: /{id}
    defaults: { _controller: AppBundle:User:edit }
    methods: GET|POST

user_index:
    path: /
    defaults: { _controller: AppBundle:User:index }
    methods: GET
